# Generated by Django 3.1.5 on 2021-01-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0003_auto_20210126_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.png', upload_to='tution/images/'),
        ),
    ]
