# Generated by Django 3.1.5 on 2021-01-29 11:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0004_auto_20210126_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Arabic', 'Arabic'), ('Hindi', 'Hindi'), ('Urdu', 'Urdu')], default='Bangla', max_length=100),
        ),
    ]
