# Generated by Django 3.1.5 on 2021-01-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0007_class_in_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='class_in',
            field=models.ManyToManyField(related_name='class_set', to='tution.Class_in'),
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.ManyToManyField(related_name='subject_set', to='tution.Subject'),
        ),
    ]
